-- MySQL Script generated by MySQL Workbench
-- Wed Sep 21 11:52:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `ecommercedb` DEFAULT CHARACTER SET utf8 ;
USE `ecommercedb` ;

-- -----------------------------------------------------
-- Table `ecommercedb`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`user_type` (
  `id` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`users` (
  `id` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `username` VARCHAR(255) NULL,
  `user_type` INT NOT NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `ecommercedb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`categories` (
  `id` INT NOT NULL,
  `category_name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`products` (
  `id` INT NOT NULL,
  `product_name` VARCHAR(45) NULL,
  `about` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `price` INT NULL,
  `category_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`favorites` (
  `client_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `product_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`cart` (
  `client_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`client_id`, `product_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`wish_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`wish_list` (
  `client_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `created_ad` TIMESTAMP NULL,
  PRIMARY KEY (`client_id`, `product_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`discount_codes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`discounts` (
  `id` INT NOT NULL,
  `discount_code` VARCHAR(255) NULL,
  `discount_percentage` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `end_at` DATETIME NULL,
  `user_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`, `product_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`reset_password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`reset_password` (
  `id` INT NOT NULL,
  `reset_password` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`images` (
  `id` INT NOT NULL,
  `image` VARCHAR(255) NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`checkouts` (
  `client_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL,
  `created_at` TIMESTAMP NULL,
  PRIMARY KEY (`client_id`, `product_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`views`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`views` (
  `product_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `client_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`ads` (
  `id` INT NOT NULL,
  `image` VARCHAR(255) NULL,
  `seller_id` INT NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`vouchers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`vouchers` (
  `client_send` INT NOT NULL,
  `client_receive` INT NOT NULL,
  `voucher_code` VARCHAR(45) NULL,
  `voucher_amount` INT NULL,
  `used` INT NULL,
  PRIMARY KEY (`client_send`, `client_receive`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`clients_has_clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`chat` (
  `client_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `massage` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`client_id`, `seller_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`lottery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`lottery` (
  `client_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `first` INT NULL,
  `second` INT NULL,
  `third` INT NULL,
  `closed` INT NULL,
  PRIMARY KEY (`client_id`, `admin_id`));


-- -----------------------------------------------------
-- Table `ecommercedb`.`ban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommercedb`.`ban` (
  `id` INT NOT NULL,
  `banned` VARCHAR(45) NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
